variables:
    RELEASE_BUCKET:
      value: "cloudfoundry.datadoghq.com/datadog-cloudfoundry-buildpack"
      description: "Bucket where the buildpack release will be stored"
    DRY_RUN:
      value: "true"
      description: "Set to true to do a dry run"
    REPO_BRANCH:
      value: "master"
      description: "The branch to use"


buildpack-prod-release:
  stage: deploy
  image: registry.ddbuild.io/ci/datadog-agent-buildimages/gitlab_agent_deploy:v48815877-9bfad02c
  tags: ["runner:main"]
  when: manual
  before_script:
    - apt-get update -y && apt-get install -y zip
  script:
    - 'export PRODUCTION=true'
    - ./scripts/release.sh
