#!/bin/bash

SRCDIR=$(cd "$(dirname $0)/." && pwd)
NAME="datadog-cloudfoundry-buildpack"
ZIPFILE="$NAME.zip"
PUPPY_DOWNLOAD_URL="https://s3.amazonaws.com/dd-agent/agent6/puppy/linux"
DOGSTATSD_DOWNLOAD_URL="https://s3.amazonaws.com/dd-agent/dsd6/dogstatsd/linux"
TRACEAGENT_DOWNLOAD_URL_HEAD="https://s3.amazonaws.com/apt.datadoghq.com/pool/d/da/datadog-agent_"
TRACEAGENT_DOWNLOAD_URL_TAIL="-1_amd64.deb"
TRACE_DEFAULT_VERSION="6.13.0"

AGENT_DEFAULT_VERSION="7.17.0"
DOTNET_TRACER_DEFAULT_VERSION="1.6.0"

AGENT_VERSION=${AGENT_VERSION:-$AGENT_DEFAULT_VERSION}
DOTNET_TRACER_VERSION=${DOTNET_TRACER_VERSION:-$DOTNET_TRACER_DEFAULT_VERSION}
AGENT_DEB_DOWNLOAD_URL="https://s3.amazonaws.com/apt.datadoghq.com/pool/d/da/datadog-agent_${AGENT_VERSION}-1_amd64.deb"
# [TODO] Update this to the zip location and uncomment the commented lines in this script
# AGENT_BINARIES_DOWNLOAD_URL="https://s3.amazonaws.com/ddagent-windows-stable/ddagent-cli-${AGENT_VERSION}.msi"
AGENT_DOTNET_TRACER_DOWNLOAD_URL="https://github.com/DataDog/dd-trace-dotnet/releases/download/v${DOTNET_TRACER_VERSION}/datadog-dotnet-apm-${DOTNET_TRACER_VERSION}-x64.msi"

if [ ! -f $SRCDIR/lib/datadog-agent.deb ] ||
  #  [ ! -f $SRCDIR/lib/agent-binaries.zip ] ||
   [ ! -f $SRCDIR/lib/dotnet-tracer.msi ] ||
   [ -n "$REFRESH_ASSETS" ]; then
  # Delete the old ones
  rm -f $SRCDIR/lib/datadog-agent.deb
  # rm -f $SRCDIR/lib/datadog-binaries.zip
  rm -f $SRCDIR/lib/dotnet-tracer.msi
  # Download the new ones
  curl $AGENT_DEB_DOWNLOAD_URL -o ./lib/datadog-agent.deb
  # curl $AGENT_MSI_DOWNLOAD_URL -o ./lib/agent-binaries.zip
  curl -L $AGENT_DOTNET_TRACER_DOWNLOAD_URL -o ./lib/dotnet-tracer.msi
fi

    if [ -n "$VERSION" ]; then
      PUPPY_DOWNLOAD_URL="$PUPPY_DOWNLOAD_URL/agent-$VERSION"
      DOGSTATSD_DOWNLOAD_URL="$DOGSTATSD_DOWNLOAD_URL/dogstatsd-$VERSION"
    else
      PUPPY_DOWNLOAD_URL="$PUPPY_DOWNLOAD_URL/agent-latest"
      DOGSTATSD_DOWNLOAD_URL="$DOGSTATSD_DOWNLOAD_URL/dogstatsd-latest"
    fi

    curl $PUPPY_DOWNLOAD_URL -o $SRCDIR/lib/puppy
    chmod +x $SRCDIR/lib/puppy

    curl $DOGSTATSD_DOWNLOAD_URL -o ./lib/dogstatsd
    chmod +x $SRCDIR/lib/dogstatsd

    # Does not support versioning for now, keep it dumb until trace-agent merge with the Agent6
    # curl -L $TRACEAGENT_DOWNLOAD_URL -o ./lib/trace-agent
    download_trace_agent $VERSION
    chmod +x $SRCDIR/lib/trace-agent
  fi

  rm -f $ZIPFILE

  pushd $SRCDIR
    if [ ! "$NO_ZIP" ]; then
      zip -r "$ZIPFILE" lib bin
    fi
  popd
}


main
