#!/bin/bash

SRCDIR=$(cd "$(dirname $0)/." && pwd)
NAME="datadog-cloudfoundry-buildpack"
ZIPFILE="$NAME.zip"
DOWNLOAD_URL="https://s3.amazonaws.com/dd-agent/dsd6/dogstatsd/linux/"

if [ ! -f ./lib/dogstatsd ]; then
  DOWNLOAD="true"
fi
if [ -n "$REFRESH_ASSETS" ]; then
  DOWNLOAD="true"
fi
if [ -n "$DOWNLOAD" ]; then
  if [ -z "$VERSION" ]; then
    echo 'You need to set the $VERSION in order to download dogstatsd, exiting...'
    exit 1
  fi

  if [ -n $VERSION]; then
    DOWNLOAD_URL="$DOWNLOAD_URL/dogstatsd-$VERSION"
  else
    DOWNLOAD_URL="$DOWNLOAD_URL/dogstatsd-latest"
  fi

  curl $DOWNLOAD_URL -o ./lib/dogstatsd
fi

rm -f $ZIPFILE

pushd $SRCDIR
  zip -r "$ZIPFILE" lib bin
popd
