#!/bin/bash

SRCDIR=$(cd "$(dirname $0)/." && pwd)
ZIPFILE="datadog-cloudfoundry-buildpack.zip"

AGENT_DEFAULT_VERSION="6.12.0"

AGENT_VERSION=${AGENT_VERSION:-$AGENT_DEFAULT_VERSION}
AGENT_DOWNLOAD_URL="https://s3.amazonaws.com/apt.datadoghq.com/pool/d/da/datadog-agent_${AGENT_VERSION}-1_amd64.deb"

if [ ! -f $SRCDIR/lib/datadog-agent.deb ] || [ -n "$REFRESH_ASSETS" ]; then
  # Delete the old one
  rm -f $SRCDIR/lib/datadog-agent.deb
  # Download the new one
  curl $AGENT_DOWNLOAD_URL -o ./lib/datadog-agent.deb
fi

# Remove old zipfile
rm -f $ZIPFILE

pushd $SRCDIR
  if [ ! "$NO_ZIP" ]; then
    zip -r "$ZIPFILE" lib bin
  fi
popd
