#!/usr/bin/env bash

# Unless explicitly stated otherwise all files in this repository are licensed under the Apache 2.0 License.
# This product includes software developed at Datadog (https://www.datadoghq.com/).
# Copyright 2017-Present Datadog, Inc.

# Datadog PHP single-step APM instrumentation.
# Installed by bin/supply as .profile.d/99-datadog-php.sh so it runs AFTER
# lib/run-datadog.sh (01-) and AFTER php_buildpack's own .profile.d scripts.

DATADOG_DIR="${DATADOG_DIR:-/home/vcap/app/.datadog}"
DD_LIBRARY_PHP_DIR="${DATADOG_DIR}/dd-library-php"
DD_PHP_INI_DIR="${DATADOG_DIR}/php/php.ini.d"

dd_php_log() {
  echo "[datadog-php] $*"
}

dd_php_main() {
  if [ -z "${DD_APM_INSTRUMENTATION_ENABLED}" ] || [ "${DD_APM_INSTRUMENTATION_ENABLED}" = "false" ]; then
    return 0
  fi

  local has_php_buildpack=""
  if [ -z "${DEPS_DIR:-}" ]; then
    return 0
  fi

  for dir in "${DEPS_DIR}"/*/; do
    dir="${dir%/}"
    if grep -q -E '^name: php$' "${dir}/config.yml" >/dev/null 2>&1; then
      has_php_buildpack="${dir}"
      break
    fi
  done
  if [ -z "${has_php_buildpack}" ]; then
    return 0
  fi

  if [ ! -d "${DD_LIBRARY_PHP_DIR}" ]; then
    local msg="dd-library-php was not bundled in this buildpack (${DD_LIBRARY_PHP_DIR} missing). The buildpack appears to have been built without scripts/prepare.sh, or with REFRESH_ASSETS unset."
    if [ "${DD_APM_INSTRUMENTATION_STRICT}" = "true" ]; then
      dd_php_log "ERROR: ${msg} DD_APM_INSTRUMENTATION_STRICT=true — failing app start."
      exit 1
    fi
    dd_php_log "WARNING: ${msg} App will start without Datadog APM instrumentation."
    return 0
  fi

  dd_php_log "PHP buildpack detected at ${has_php_buildpack}; configuring tracer"

  local php_bin=""
  if command -v php >/dev/null 2>&1; then
    php_bin="$(command -v php)"
  elif [ -x "${HOME}/php/bin/php" ]; then
    php_bin="${HOME}/php/bin/php"
  elif [ -x "${has_php_buildpack}/bin/php" ]; then
    php_bin="${has_php_buildpack}/bin/php"
  fi
  if [ -z "${php_bin}" ]; then
    dd_php_log "WARNING: php binary not found on PATH or in standard locations; skipping tracer setup"
    return 0
  fi

  local php_api
  php_api="$("${php_bin}" -i 2>/dev/null | sed -n 's/^PHP API => //p' | head -1 | tr -d '[:space:]')"
  if [ -z "${php_api}" ]; then
    dd_php_log "WARNING: could not resolve PHP API version from '${php_bin} -i'; skipping tracer setup"
    return 0
  fi
  dd_php_log "resolved PHP API: ${php_api}"

  local tracer_so="${DD_LIBRARY_PHP_DIR}/trace/ext/${php_api}/ddtrace.so"
  local profiler_so="${DD_LIBRARY_PHP_DIR}/profiling/ext/${php_api}/datadog-profiling.so"
  local trace_src="${DD_LIBRARY_PHP_DIR}/trace/src"

  if [ ! -f "${tracer_so}" ]; then
    local bundled_apis
    bundled_apis="$(ls -1 "${DD_LIBRARY_PHP_DIR}/trace/ext" 2>/dev/null | tr '\n' ' ')"
    local bundled_version="(unknown)"
    if [ -f "${DD_LIBRARY_PHP_DIR}/VERSION" ]; then
      bundled_version="$(cat "${DD_LIBRARY_PHP_DIR}/VERSION")"
    fi
    local msg="dd-library-php ${bundled_version} does not include a tracer build for PHP API ${php_api}. Bundled APIs: ${bundled_apis}."
    if [ "${DD_APM_INSTRUMENTATION_STRICT}" = "true" ]; then
      dd_php_log "ERROR: ${msg} DD_APM_INSTRUMENTATION_STRICT=true — failing app start."
      exit 1
    fi
    dd_php_log "WARNING: ${msg} App will start without Datadog APM instrumentation."
    return 0
  fi

  if [ "${DD_PROFILING_ENABLED}" = "true" ] && [ ! -f "${profiler_so}" ]; then
    dd_php_log "WARNING: DD_PROFILING_ENABLED=true but ${profiler_so} is missing; profiling will be disabled for this app."
  fi

  mkdir -p "${DD_PHP_INI_DIR}"
  {
    echo "; Generated by datadog-cloudfoundry-buildpack 99-datadog-php.sh"
    echo "extension=${tracer_so}"
    if [ "${DD_PROFILING_ENABLED}" = "true" ] && [ -f "${profiler_so}" ]; then
      echo "extension=${profiler_so}"
    fi
    if [ -d "${trace_src}" ]; then
      echo "datadog.trace.sources_path=${trace_src}"
    fi
  } > "${DD_PHP_INI_DIR}/datadog.ini"

  export PHP_INI_SCAN_DIR="${PHP_INI_SCAN_DIR}:${DD_PHP_INI_DIR}"
  dd_php_log "wrote ${DD_PHP_INI_DIR}/datadog.ini and exported PHP_INI_SCAN_DIR"
}

dd_php_main
