name: "Pull Request Labeler"
on:
  - pull_request

jobs:
  triage:
    runs-on: ubuntu-latest
    permissions:
        contents: write
    steps:
      - uses: DataDog/labeler@glob-all
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
